//SWITCH RENDER---------------
export const SWITCH_RENDER = "SWITCH_RENDER";
//GET ALL------------------
export const GET_ALL_PETS = "GET_ALL_PETS";
export const GET_ALL_USERS = "GET_ALL_USERS";
//GET DETAIL---------------
export const GET_PET_DETAIL = "GET_PET_DETAIL";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const CLEAR_STATE = "CLEAR_STATE";
export const CLEAR_STATE_PET = "CLEAR_STATE_PET";
//GET BY NAME------------------
export const GET_USER_BY_NAME = "GET_USER_BY_NAME";
export const GET_PET_BY_NAME = "GET_PET_BY_NAME";
//POST-----------------
export const POST_PET = "POST_PET";
export const POST_USER = "POST_USER";

export const POST_IMAGE = "POST_IMAGE";
//UPDATE----------------
export const POST_ADOPTION = "POST_ADOPTION"; //OK
//THE UPDATE----------------
export const PATCH_USER = "PATCH_USER";
export const PATCH_PET = "PATCH_PET";
export const PATCH_LIKES = "PATCH_LIKES";
//FILTERS -----------------
export const FILTER_BY_QUERY = "FILTER_BY_QUERY";
//LOGIN -----------------
export const USER_LOGIN = "USER_LOGIN";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const USER_LOGIN_GOOGLE = "USER_LOGIN_GOOGLE";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
//ADOPT ------------------
export const ADOPT = "ADOPT";
export const ADOPT_EMAIL = "ADOPT_EMAIL";
//PAYMENT -------------------
export const PAYMENT_MP = "PAYMENT_MP";
export const PAYMENT_MERP = "PAYMENT_MERP";//DEMARKET
export const PAYMENT_CART = "PAYMENT_CART";//DEMARKET
//INTERESTED_USERS
export const INTERESTED_USERS = "INTERESTED_USERS";

export const NOTIFICATION = "NOTIFICATION";
//CHAT
export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const GET_MESSAGES = "GET_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const CHAT_WITH_USER = "CHAT_WITH_USER";

export const VIEWED_NOTIFICATION = "VIEWED_NOTIFICATION";
export const NOT_VIEWED_NOTIFICATION = "NOT_VIEWED_NOTIFICATION";
export const VIEWING_NOTIFICATION = "VIEWING_NOTIFICATION";
export const VIEWING_LIKE_NOTIFICATION = "VIEWING_LIKE_NOTIFICATION";
export const LIKE_PET = "LIKE_PET";
export const REPORT_PET = "REPORT_PET";
export const REPORT_USER = "REPORT_USER";
export const GET_REPORTED_PETS = "GET_REPORTED_PETS";
export const GET_REPORTED_USERS = "GET_REPORTED_USERS";
export const HANDLE_PET = "HANDLE_PET";
export const HANDLE_USER = "HANDLE_USER";
export const HANDLE_PET_REPORT = "HANDLE_PET_REPORT";
export const HANDLE_USER_REPORT = "HANDLE_USER_REPORT";
export const HANDLE_ADMIN = "HANDLE_ADMIN";
export const GET_DELETED_PETS = "GET_DELETED_PETS";
export const GET_DELETED_USERS = "GET_DELETED_USERS";
export const HANDLE_USER_RESTORE = "HANDLE_USER_RESTORE";
export const HANDLE_USER_REPORT_RESTORE = "HANDLE_USER_REPORT_RESTORE";
export const GET_USER_REPORTS_SOLVED = "GET_USER_REPORTS_SOLVED";
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const GET_PRODUCT_NAME = "GET_PRODUCT_NAME"
export const CLEAR_PRODUCT_DETAIL = "CLEAR_PRODUCT_DETAIL"
export const ADD_CAR = "ADD_CAR"
export const FILTROS_MARKET = "FILTROS_MARKET"
export const DEL_PRODUCT_CART = "DEL_PRODUCT_CART"

